#!/usr/bin/env ruby
require 'curb'
c = Curl::Easy.new "http://140.109.22.239/index.php?option=com_ofsso&controller=sso&task=syncusers"

c.http_post(
 Curl::PostField.content('data', User.all.to_json) 
)
puts c.response_code
